version: '3.8'

networks:
  db:
  prisma:
  core:
  frontend:

volumes:
  postgres:
  web:

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - db
      - core

  forum-world-core:
    container_name: forum-world-core
    image: 777lk777/forum-world-project-forum-world-core:latest
    environment:
      FW_CORE_PORT: ${FW_CORE_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - web:/forum-world-core/app
      - /forum-world-core/app/node_modules
    ports:
      - "${FW_CORE_PORT}:${FW_CORE_PORT}"
    depends_on:
      - postgres
    command: npm run ${CORE_RUN_CMD}
    restart: always
    networks:
      - core

  forum-world-gateway:
    container_name: forum-world-gateway
    image: 777lk777/forum-world-project-forum-world-gateway:latest
    environment:
      FW_GATEWAY_PORT: ${FW_GATEWAY_PORT}
      FW_UI_PORT: ${FW_UI_PORT}
      FW_UI_ORIGIN: ${FW_UI_ORIGIN}
      FW_CORE_ORIGIN: ${FW_CORE_ORIGIN}
      HOST_IP: ${FW_GATEWAY_LOCAL_ORIGIN}
      HOST_PORT: ${FW_GATEWAY_PORT}
    volumes:
      - web:/forum-world-gateway
      - /forum-world-gateway/app/node_modules
    ports:
      - "${FW_GATEWAY_PORT}:${FW_GATEWAY_PORT}"
      - "${HOST_IP}:${HOST_PORT}:${FW_GATEWAY_PORT}"
    depends_on:
      - forum-world-core
    command: npm run ${GATEWAY_RUN_CMD}
    restart: always
    networks:
      - core
      - frontend
