version: '3.8'

networks:
  db:
  prisma:
  core:
  frontend:

volumes:
  postgres:
  prisma:
  web:

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - db
      - core

  # forum-world-prisma:
  #   container_name: forum-world-prisma
  #   image: prismagraphql/prisma:1.10
  #   restart: always
  #   ports:
  #     - "4466:4466"
  #   environment:
  #     SLOW_QUERIES_LOGGING: 'true'
  #     SLOW_QUERIES_LOGGING_THRESHOLD: '0'
  #     PRISMA_CONFIG: |
  #       managementApiSecret: ${PRISMA_API_SECRET}
  #       port: 4466
  #       databases:
  #         default:
  #           connector: "postgres"
  #           host: "postgres"
  #           port: 5432
  #           user: ${DB_USER}
  #           password: ${DB_PASSWORD}
  #           database: ${DB_NAME}
  #           databases: "public"
  #       service:
  #         env: production
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - prisma:/app
  #   networks:
  #     - db
  #     - prisma

  forum-world-core:
    container_name: forum-world-core
    build:
      context: ./forum-world-core
      args:
        - FW_CORE_PORT=${FW_CORE_PORT}
        - DATABASE_URL=${DATABASE_URL}
    volumes:
      - web:/forum-world-core/app
      - /forum-world-core/app/node_modules
    ports:
      - "${FW_CORE_PORT}:${FW_CORE_PORT}"
    depends_on:
      - postgres
    command: npm run ${CORE_RUN_CMD}
    restart: always
    networks:
      - core

  forum-world-gateway:
    container_name: forum-world-gateway
    build:
      context: ./forum-world-gateway
      args:
        - FW_GATEWAY_PORT=${FW_GATEWAY_PORT}
        - FW_UI_PORT=${FW_UI_PORT}
        - FW_UI_ORIGIN=${FW_UI_ORIGIN}
        - FW_CORE_ORIGIN=${FW_CORE_ORIGIN}
    volumes:
      - web:/forum-world-gateway
      - /forum-world-gateway/app/node_modules
    environment:
      - HOST_IP=${FW_GATEWAY_LOCAL_ORIGIN}
      - HOST_PORT=${FW_GATEWAY_PORT}
    ports:
      - "${FW_GATEWAY_PORT}:${FW_GATEWAY_PORT}"
      - "${HOST_IP}:${HOST_PORT}:${FW_GATEWAY_PORT}"
    depends_on:
      - forum-world-core
    command: npm run ${GATEWAY_RUN_CMD}
    restart: always
    networks:
      - core
      - frontend
      
  forum-world-ui:
    container_name: forum-world-ui
    build:
      context: ./forum-world-ui
    volumes:
      - web:/forum-world-ui
      - /forum-world-ui/app/node_modules
    ports:
      - "${FW_UI_PORT}:${FW_UI_PORT}"
    depends_on:
      - forum-world-gateway
    command: npm run ${UI_RUN_CMD} -- -p ${FW_UI_PORT}
    restart: always
    networks:
      - frontend
